# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test7.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow1(object):
    def setupUi(self, MainWindow1):
        MainWindow1.setObjectName("MainWindow1")
        MainWindow1.resize(1100, 600)
        MainWindow1.setMinimumSize(QtCore.QSize(1100, 600))
        MainWindow1.setMaximumSize(QtCore.QSize(1100, 600))
        MainWindow1.setStyleSheet("background-color:rgb(103, 116, 166);")
        self.centralwidget = QtWidgets.QWidget(MainWindow1)
        self.centralwidget.setObjectName("centralwidget")
        self.label_left = QtWidgets.QLabel(self.centralwidget)
        self.label_left.setGeometry(QtCore.QRect(10, 0, 511, 571))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(20)
        self.label_left.setFont(font)
        self.label_left.setStyleSheet("background-color:transparent;\n"
"border:1px solid rgb(255, 255, 255);\n"
"border-top-left-radius:5px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"color:rgb(255, 255, 255);\n"
"")
        self.label_left.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_left.setObjectName("label_left")
        self.label_right = QtWidgets.QLabel(self.centralwidget)
        self.label_right.setGeometry(QtCore.QRect(530, 0, 561, 571))
        self.label_right.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(20)
        self.label_right.setFont(font)
        self.label_right.setStyleSheet("background-color:transparent;\n"
"border:1px solid rgb(255, 255, 255);\n"
"border-top-left-radius:5px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"color:rgb(255, 255, 255);\n"
"")
        self.label_right.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_right.setObjectName("label_right")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(20, 60, 491, 381))
        font = QtGui.QFont()
        font.setFamily("Hobo Std")
        font.setPointSize(12)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setStyleSheet("alternate-background-color: rgb(160, 160, 160);\n"
"selection-color: rgb(247, 102, 119);\n"
"selection-background-color: rgb(185, 183, 186);\n"
"selection-background-color: rgb(233, 193, 76);\n"
"background-color: rgb(255, 255, 191);")
        self.calendarWidget.setObjectName("calendarWidget")
        self.pushButton_fanhui = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_fanhui.setGeometry(QtCore.QRect(540, 460, 541, 91))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_fanhui.setFont(font)
        self.pushButton_fanhui.setStyleSheet("QPushButton{\n"
"border:1px solid rgb(255, 255, 255);\n"
"border-top-left-radius:5px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"font: 14pt \"楷体\";\n"
"color:rgb(255, 255, 255);\n"
"background-color:rgb(103, 116, 166);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(123, 140, 199);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgb(83, 95, 135);\n"
"}\n"
"")
        self.pushButton_fanhui.setObjectName("pushButton_fanhui")
        self.pushButton_daochu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_daochu.setGeometry(QtCore.QRect(540, 350, 541, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_daochu.sizePolicy().hasHeightForWidth())
        self.pushButton_daochu.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_daochu.setFont(font)
        self.pushButton_daochu.setStyleSheet("QPushButton{\n"
"border:1px solid rgb(255, 255, 255);\n"
"border-top-left-radius:5px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"font: 14pt \"楷体\";\n"
"color:rgb(255, 255, 255);\n"
"background-color:rgb(103, 116, 166);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(123, 140, 199);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgb(83, 95, 135);\n"
"}\n"
"")
        self.pushButton_daochu.setObjectName("pushButton_daochu")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(30, 460, 191, 91))
        self.comboBox.setStyleSheet("font: 14pt \"楷体\";\n"
"background-color:rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_chaxu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_chaxu.setGeometry(QtCore.QRect(240, 460, 261, 91))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_chaxu.setFont(font)
        self.pushButton_chaxu.setStyleSheet("QPushButton{\n"
"border:1px solid rgb(255, 255, 255);\n"
"border-top-left-radius:5px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"font: 14pt \"楷体\";\n"
"color:rgb(255, 255, 255);\n"
"background-color:rgb(103, 116, 166);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(123, 140, 199);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgb(83, 95, 135);\n"
"}\n"
"")
        self.pushButton_chaxu.setObjectName("pushButton_chaxu")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(540, 60, 531, 281))
        self.scrollArea.setStyleSheet("background-color:rgb(103, 116, 166);")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 516, 2170))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 2170))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_number1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number1.setGeometry(QtCore.QRect(170, 180, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number1.setFont(font)
        self.label_number1.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number1.setObjectName("label_number1")
        self.label_name1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name1.setGeometry(QtCore.QRect(170, 90, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name1.setFont(font)
        self.label_name1.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name1.setObjectName("label_name1")
        self.label_name1_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name1_.setGeometry(QtCore.QRect(260, 90, 191, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name1_.setFont(font)
        self.label_name1_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name1_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name1_.setObjectName("label_name1_")
        self.label_photo_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_photo_1.setGeometry(QtCore.QRect(10, 70, 141, 191))
        font = QtGui.QFont()
        font.setFamily("Hobo Std")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_photo_1.setFont(font)
        self.label_photo_1.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_photo_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_photo_1.setObjectName("label_photo_1")
        self.label_number1_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number1_.setGeometry(QtCore.QRect(260, 180, 191, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number1_.setFont(font)
        self.label_number1_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number1_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number1_.setObjectName("label_number1_")
        self.label_number2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number2.setGeometry(QtCore.QRect(170, 390, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number2.setFont(font)
        self.label_number2.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number2.setObjectName("label_number2")
        self.label_name2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name2.setGeometry(QtCore.QRect(170, 300, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name2.setFont(font)
        self.label_name2.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name2.setObjectName("label_name2")
        self.label_name2_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name2_.setGeometry(QtCore.QRect(260, 300, 191, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name2_.setFont(font)
        self.label_name2_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name2_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name2_.setObjectName("label_name2_")
        self.label_number2_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number2_.setGeometry(QtCore.QRect(260, 390, 191, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number2_.setFont(font)
        self.label_number2_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number2_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number2_.setObjectName("label_number2_")
        self.label_photo_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_photo_2.setGeometry(QtCore.QRect(10, 280, 141, 191))
        font = QtGui.QFont()
        font.setFamily("Hobo Std")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_photo_2.setFont(font)
        self.label_photo_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_photo_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_photo_2.setObjectName("label_photo_2")
        self.label_tishi = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_tishi.setGeometry(QtCore.QRect(20, 10, 471, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_tishi.setFont(font)
        self.label_tishi.setStyleSheet("background-color:transparent; \n"
"color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-bottom:1px solid rgb(255, 255, 255);")
        self.label_tishi.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tishi.setObjectName("label_tishi")
        self.label_name3_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name3_.setGeometry(QtCore.QRect(260, 510, 191, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name3_.setFont(font)
        self.label_name3_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name3_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name3_.setObjectName("label_name3_")
        self.label_number3_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number3_.setGeometry(QtCore.QRect(260, 600, 191, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number3_.setFont(font)
        self.label_number3_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number3_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number3_.setObjectName("label_number3_")
        self.label_name4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name4.setGeometry(QtCore.QRect(170, 720, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name4.setFont(font)
        self.label_name4.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name4.setObjectName("label_name4")
        self.label_name4_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name4_.setGeometry(QtCore.QRect(260, 720, 191, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name4_.setFont(font)
        self.label_name4_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name4_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name4_.setObjectName("label_name4_")
        self.label_number4_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number4_.setGeometry(QtCore.QRect(260, 810, 191, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number4_.setFont(font)
        self.label_number4_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number4_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number4_.setObjectName("label_number4_")
        self.label_number4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number4.setGeometry(QtCore.QRect(170, 810, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number4.setFont(font)
        self.label_number4.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number4.setObjectName("label_number4")
        self.label_photo_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_photo_4.setGeometry(QtCore.QRect(10, 700, 141, 191))
        font = QtGui.QFont()
        font.setFamily("Hobo Std")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_photo_4.setFont(font)
        self.label_photo_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_photo_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_photo_4.setObjectName("label_photo_4")
        self.label_number3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number3.setGeometry(QtCore.QRect(170, 600, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number3.setFont(font)
        self.label_number3.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number3.setObjectName("label_number3")
        self.label_photo_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_photo_3.setGeometry(QtCore.QRect(10, 490, 141, 191))
        font = QtGui.QFont()
        font.setFamily("Hobo Std")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_photo_3.setFont(font)
        self.label_photo_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_photo_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_photo_3.setObjectName("label_photo_3")
        self.label_name3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name3.setGeometry(QtCore.QRect(170, 510, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name3.setFont(font)
        self.label_name3.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name3.setObjectName("label_name3")
        self.label_name5_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name5_.setGeometry(QtCore.QRect(260, 930, 191, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name5_.setFont(font)
        self.label_name5_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name5_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name5_.setObjectName("label_name5_")
        self.label_number5_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number5_.setGeometry(QtCore.QRect(260, 1020, 191, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number5_.setFont(font)
        self.label_number5_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number5_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number5_.setObjectName("label_number5_")
        self.label_name6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name6.setGeometry(QtCore.QRect(170, 1140, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name6.setFont(font)
        self.label_name6.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name6.setObjectName("label_name6")
        self.label_name6_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name6_.setGeometry(QtCore.QRect(260, 1140, 191, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name6_.setFont(font)
        self.label_name6_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name6_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name6_.setObjectName("label_name6_")
        self.label_number6_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number6_.setGeometry(QtCore.QRect(260, 1230, 191, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number6_.setFont(font)
        self.label_number6_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number6_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number6_.setObjectName("label_number6_")
        self.label_number6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number6.setGeometry(QtCore.QRect(170, 1230, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number6.setFont(font)
        self.label_number6.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number6.setObjectName("label_number6")
        self.label_photo_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_photo_6.setGeometry(QtCore.QRect(10, 1120, 141, 191))
        font = QtGui.QFont()
        font.setFamily("Hobo Std")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_photo_6.setFont(font)
        self.label_photo_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_photo_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_photo_6.setObjectName("label_photo_6")
        self.label_number5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number5.setGeometry(QtCore.QRect(170, 1020, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number5.setFont(font)
        self.label_number5.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number5.setObjectName("label_number5")
        self.label_photo_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_photo_5.setGeometry(QtCore.QRect(10, 910, 141, 191))
        font = QtGui.QFont()
        font.setFamily("Hobo Std")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_photo_5.setFont(font)
        self.label_photo_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_photo_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_photo_5.setObjectName("label_photo_5")
        self.label_name5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name5.setGeometry(QtCore.QRect(170, 930, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name5.setFont(font)
        self.label_name5.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name5.setObjectName("label_name5")
        self.label_name7_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name7_.setGeometry(QtCore.QRect(260, 1350, 191, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name7_.setFont(font)
        self.label_name7_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name7_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name7_.setObjectName("label_name7_")
        self.label_number7_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number7_.setGeometry(QtCore.QRect(260, 1440, 191, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number7_.setFont(font)
        self.label_number7_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number7_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number7_.setObjectName("label_number7_")
        self.label_name8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name8.setGeometry(QtCore.QRect(170, 1560, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name8.setFont(font)
        self.label_name8.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name8.setObjectName("label_name8")
        self.label_name8_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name8_.setGeometry(QtCore.QRect(260, 1560, 191, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name8_.setFont(font)
        self.label_name8_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name8_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name8_.setObjectName("label_name8_")
        self.label_number8_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number8_.setGeometry(QtCore.QRect(260, 1650, 191, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number8_.setFont(font)
        self.label_number8_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number8_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number8_.setObjectName("label_number8_")
        self.label_number8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number8.setGeometry(QtCore.QRect(170, 1650, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number8.setFont(font)
        self.label_number8.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number8.setObjectName("label_number8")
        self.label_photo_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_photo_8.setGeometry(QtCore.QRect(10, 1540, 141, 191))
        font = QtGui.QFont()
        font.setFamily("Hobo Std")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_photo_8.setFont(font)
        self.label_photo_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_photo_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_photo_8.setObjectName("label_photo_8")
        self.label_number7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number7.setGeometry(QtCore.QRect(170, 1440, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number7.setFont(font)
        self.label_number7.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number7.setObjectName("label_number7")
        self.label_photo_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_photo_7.setGeometry(QtCore.QRect(10, 1330, 141, 191))
        font = QtGui.QFont()
        font.setFamily("Hobo Std")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_photo_7.setFont(font)
        self.label_photo_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_photo_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_photo_7.setObjectName("label_photo_7")
        self.label_name7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name7.setGeometry(QtCore.QRect(170, 1350, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name7.setFont(font)
        self.label_name7.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name7.setObjectName("label_name7")
        self.label_name9_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name9_.setGeometry(QtCore.QRect(260, 1770, 191, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name9_.setFont(font)
        self.label_name9_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name9_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name9_.setObjectName("label_name9_")
        self.label_number9_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number9_.setGeometry(QtCore.QRect(260, 1860, 191, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number9_.setFont(font)
        self.label_number9_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number9_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number9_.setObjectName("label_number9_")
        self.label_name10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name10.setGeometry(QtCore.QRect(170, 1980, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name10.setFont(font)
        self.label_name10.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name10.setObjectName("label_name10")
        self.label_name10_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name10_.setGeometry(QtCore.QRect(260, 1980, 191, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name10_.setFont(font)
        self.label_name10_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name10_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name10_.setObjectName("label_name10_")
        self.label_number10_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number10_.setGeometry(QtCore.QRect(260, 2070, 191, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number10_.setFont(font)
        self.label_number10_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number10_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number10_.setObjectName("label_number10_")
        self.label_number10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number10.setGeometry(QtCore.QRect(170, 2070, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number10.setFont(font)
        self.label_number10.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number10.setObjectName("label_number10")
        self.label_photo_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_photo_10.setGeometry(QtCore.QRect(10, 1960, 141, 191))
        font = QtGui.QFont()
        font.setFamily("Hobo Std")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_photo_10.setFont(font)
        self.label_photo_10.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_photo_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_photo_10.setObjectName("label_photo_10")
        self.label_number9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number9.setGeometry(QtCore.QRect(170, 1860, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number9.setFont(font)
        self.label_number9.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number9.setObjectName("label_number9")
        self.label_photo_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_photo_9.setGeometry(QtCore.QRect(10, 1750, 141, 191))
        font = QtGui.QFont()
        font.setFamily("Hobo Std")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_photo_9.setFont(font)
        self.label_photo_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_photo_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_photo_9.setObjectName("label_photo_9")
        self.label_name9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name9.setGeometry(QtCore.QRect(170, 1770, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name9.setFont(font)
        self.label_name9.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name9.setObjectName("label_name9")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 18))
        self.menubar.setObjectName("menubar")
        MainWindow1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow1)
        self.statusbar.setObjectName("statusbar")
        MainWindow1.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow1)

    def retranslateUi(self, MainWindow1):
        _translate = QtCore.QCoreApplication.translate
        MainWindow1.setWindowTitle(_translate("MainWindow1", "MainWindow"))
        self.label_left.setText(_translate("MainWindow1", "按时间查询未佩戴人员"))
        self.label_right.setText(_translate("MainWindow1", "未佩戴人员信息"))
        self.pushButton_fanhui.setText(_translate("MainWindow1", "< 返回主页面"))
        self.pushButton_daochu.setText(_translate("MainWindow1", "导出未配戴人员名单"))
        self.comboBox.setItemText(0, _translate("MainWindow1", "上午"))
        self.comboBox.setItemText(1, _translate("MainWindow1", "下午"))
        self.pushButton_chaxu.setText(_translate("MainWindow1", "查询"))
        self.label_number1.setText(_translate("MainWindow1", "工号："))
        self.label_name1.setText(_translate("MainWindow1", "姓名："))
        self.label_name1_.setText(_translate("MainWindow1", "XXX"))
        self.label_photo_1.setText(_translate("MainWindow1", "photo"))
        self.label_number1_.setText(_translate("MainWindow1", "XXX"))
        self.label_number2.setText(_translate("MainWindow1", "工号："))
        self.label_name2.setText(_translate("MainWindow1", "姓名："))
        self.label_name2_.setText(_translate("MainWindow1", "XXX"))
        self.label_number2_.setText(_translate("MainWindow1", "XXX"))
        self.label_photo_2.setText(_translate("MainWindow1", "photo"))
        self.label_tishi.setText(_translate("MainWindow1", "查询到：xx人，显示：xx人，详情请导出"))
        self.label_name3_.setText(_translate("MainWindow1", "XXX"))
        self.label_number3_.setText(_translate("MainWindow1", "XXX"))
        self.label_name4.setText(_translate("MainWindow1", "姓名："))
        self.label_name4_.setText(_translate("MainWindow1", "XXX"))
        self.label_number4_.setText(_translate("MainWindow1", "XXX"))
        self.label_number4.setText(_translate("MainWindow1", "工号："))
        self.label_photo_4.setText(_translate("MainWindow1", "photo"))
        self.label_number3.setText(_translate("MainWindow1", "工号："))
        self.label_photo_3.setText(_translate("MainWindow1", "photo"))
        self.label_name3.setText(_translate("MainWindow1", "姓名："))
        self.label_name5_.setText(_translate("MainWindow1", "XXX"))
        self.label_number5_.setText(_translate("MainWindow1", "XXX"))
        self.label_name6.setText(_translate("MainWindow1", "姓名："))
        self.label_name6_.setText(_translate("MainWindow1", "XXX"))
        self.label_number6_.setText(_translate("MainWindow1", "XXX"))
        self.label_number6.setText(_translate("MainWindow1", "工号："))
        self.label_photo_6.setText(_translate("MainWindow1", "photo"))
        self.label_number5.setText(_translate("MainWindow1", "工号："))
        self.label_photo_5.setText(_translate("MainWindow1", "photo"))
        self.label_name5.setText(_translate("MainWindow1", "姓名："))
        self.label_name7_.setText(_translate("MainWindow1", "XXX"))
        self.label_number7_.setText(_translate("MainWindow1", "XXX"))
        self.label_name8.setText(_translate("MainWindow1", "姓名："))
        self.label_name8_.setText(_translate("MainWindow1", "XXX"))
        self.label_number8_.setText(_translate("MainWindow1", "XXX"))
        self.label_number8.setText(_translate("MainWindow1", "工号："))
        self.label_photo_8.setText(_translate("MainWindow1", "photo"))
        self.label_number7.setText(_translate("MainWindow1", "工号："))
        self.label_photo_7.setText(_translate("MainWindow1", "photo"))
        self.label_name7.setText(_translate("MainWindow1", "姓名："))
        self.label_name9_.setText(_translate("MainWindow1", "XXX"))
        self.label_number9_.setText(_translate("MainWindow1", "XXX"))
        self.label_name10.setText(_translate("MainWindow1", "姓名："))
        self.label_name10_.setText(_translate("MainWindow1", "XXX"))
        self.label_number10_.setText(_translate("MainWindow1", "XXX"))
        self.label_number10.setText(_translate("MainWindow1", "工号："))
        self.label_photo_10.setText(_translate("MainWindow1", "photo"))
        self.label_number9.setText(_translate("MainWindow1", "工号："))
        self.label_photo_9.setText(_translate("MainWindow1", "photo"))
        self.label_name9.setText(_translate("MainWindow1", "姓名："))
        self.label_number1.setVisible(False)
        self.label_name1.setVisible(False)
        self.label_name1_.setVisible(False)
        self.label_photo_1.setVisible(False)
        self.label_number1_.setVisible(False)
        self.label_number2.setVisible(False)
        self.label_name2.setVisible(False)
        self.label_name2_.setVisible(False)
        self.label_number2_.setVisible(False)
        self.label_photo_2.setVisible(False)
        self.label_tishi.setVisible(False)
        self.label_name3_.setVisible(False)
        self.label_number3_.setVisible(False)
        self.label_name4.setVisible(False)
        self.label_name4_.setVisible(False)
        self.label_number4_.setVisible(False)
        self.label_number4.setVisible(False)
        self.label_photo_4.setVisible(False)
        self.label_number3.setVisible(False)
        self.label_photo_3.setVisible(False)
        self.label_name3.setVisible(False)
        self.label_name5_.setVisible(False)
        self.label_number5_.setVisible(False)
        self.label_name6.setVisible(False)
        self.label_name6_.setVisible(False)
        self.label_number6_.setVisible(False)
        self.label_number6.setVisible(False)
        self.label_photo_6.setVisible(False)
        self.label_number5.setVisible(False)
        self.label_photo_5.setVisible(False)
        self.label_name5.setVisible(False)
        self.label_name7_.setVisible(False)
        self.label_number7_.setVisible(False)
        self.label_name8.setVisible(False)
        self.label_name8_.setVisible(False)
        self.label_number8_.setVisible(False)
        self.label_number8.setVisible(False)
        self.label_photo_8.setVisible(False)
        self.label_number7.setVisible(False)
        self.label_photo_7.setVisible(False)
        self.label_name7.setVisible(False)
        self.label_name9_.setVisible(False)
        self.label_number9_.setVisible(False)
        self.label_name10.setVisible(False)
        self.label_name10_.setVisible(False)
        self.label_number10_.setVisible(False)
        self.label_number10.setVisible(False)
        self.label_photo_10.setVisible(False)
        self.label_number9.setVisible(False)
        self.label_photo_9.setVisible(False)
        self.label_name9.setVisible(False)