# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test8.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 950)
        MainWindow.setMinimumSize(QtCore.QSize(1500, 950))
        MainWindow.setStyleSheet("background-color:rgb(103, 116, 166);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_left1 = QtWidgets.QLabel(self.centralwidget)
        self.label_left1.setMinimumSize(QtCore.QSize(0, 50))
        self.label_left1.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(18)
        self.label_left1.setFont(font)
        self.label_left1.setStyleSheet("background-color:transparent; \n"
"color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-bottom:1px solid rgb(255, 255, 255);")
        self.label_left1.setTextFormat(QtCore.Qt.AutoText)
        self.label_left1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_left1.setObjectName("label_left1")
        self.verticalLayout_3.addWidget(self.label_left1)
        self.label_video = QtWidgets.QLabel(self.centralwidget)
        self.label_video.setMinimumSize(QtCore.QSize(0, 600))
        font = QtGui.QFont()
        font.setFamily("Hobo Std")
        font.setPointSize(50)
        font.setBold(False)
        font.setWeight(50)
        self.label_video.setFont(font)
        self.label_video.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_video.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"border:1px solid rgb(255, 255, 255);\n"
"color:rgb(255, 255, 255);\n"
"border-top-left-radius:5px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius:5px;")
        self.label_video.setAlignment(QtCore.Qt.AlignCenter)
        self.label_video.setObjectName("label_video")
        self.verticalLayout_3.addWidget(self.label_video)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setStyleSheet("background-color:rgb(103, 116, 166)")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1163, 1170))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 1170))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_photo_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_photo_1.setGeometry(QtCore.QRect(10, 80, 171, 191))
        font = QtGui.QFont()
        font.setFamily("Hobo Std")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_photo_1.setFont(font)
        self.label_photo_1.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_photo_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_photo_1.setObjectName("label_photo_1")
        self.label_name1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name1.setGeometry(QtCore.QRect(210, 110, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name1.setFont(font)
        self.label_name1.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name1.setObjectName("label_name1")
        self.label_name1_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name1_.setGeometry(QtCore.QRect(300, 110, 161, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name1_.setFont(font)
        self.label_name1_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name1_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name1_.setObjectName("label_name1_")
        self.label_number1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number1.setGeometry(QtCore.QRect(210, 180, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number1.setFont(font)
        self.label_number1.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number1.setObjectName("label_number1")
        self.label_number1_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number1_.setGeometry(QtCore.QRect(300, 180, 161, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number1_.setFont(font)
        self.label_number1_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number1_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number1_.setObjectName("label_number1_")
        self.label_number2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number2.setGeometry(QtCore.QRect(730, 180, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number2.setFont(font)
        self.label_number2.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number2.setObjectName("label_number2")
        self.label_name2_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name2_.setGeometry(QtCore.QRect(820, 110, 161, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name2_.setFont(font)
        self.label_name2_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name2_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name2_.setObjectName("label_name2_")
        self.label_photo_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_photo_2.setGeometry(QtCore.QRect(530, 80, 171, 191))
        font = QtGui.QFont()
        font.setFamily("Hobo Std")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_photo_2.setFont(font)
        self.label_photo_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_photo_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_photo_2.setObjectName("label_photo_2")
        self.label_name2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name2.setGeometry(QtCore.QRect(730, 110, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name2.setFont(font)
        self.label_name2.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name2.setObjectName("label_name2")
        self.label_number2_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number2_.setGeometry(QtCore.QRect(820, 180, 161, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number2_.setFont(font)
        self.label_number2_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number2_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number2_.setObjectName("label_number2_")
        self.label_number3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number3.setGeometry(QtCore.QRect(210, 400, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number3.setFont(font)
        self.label_number3.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number3.setObjectName("label_number3")
        self.label_name3_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name3_.setGeometry(QtCore.QRect(300, 330, 161, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name3_.setFont(font)
        self.label_name3_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name3_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name3_.setObjectName("label_name3_")
        self.label_photo_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_photo_3.setGeometry(QtCore.QRect(10, 300, 171, 191))
        font = QtGui.QFont()
        font.setFamily("Hobo Std")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_photo_3.setFont(font)
        self.label_photo_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_photo_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_photo_3.setObjectName("label_photo_3")
        self.label_name3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name3.setGeometry(QtCore.QRect(210, 330, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name3.setFont(font)
        self.label_name3.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name3.setObjectName("label_name3")
        self.label_number3_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number3_.setGeometry(QtCore.QRect(300, 400, 161, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number3_.setFont(font)
        self.label_number3_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number3_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number3_.setObjectName("label_number3_")
        self.tishi = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.tishi.setGeometry(QtCore.QRect(70, 10, 851, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tishi.setFont(font)
        self.tishi.setStyleSheet("background-color:transparent; \n"
"color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-bottom:1px solid rgb(255, 255, 255);")
        self.tishi.setAlignment(QtCore.Qt.AlignCenter)
        self.tishi.setObjectName("tishi")
        self.label_number4_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number4_.setGeometry(QtCore.QRect(820, 400, 161, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number4_.setFont(font)
        self.label_number4_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number4_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number4_.setObjectName("label_number4_")
        self.label_photo_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_photo_4.setGeometry(QtCore.QRect(530, 300, 171, 191))
        font = QtGui.QFont()
        font.setFamily("Hobo Std")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_photo_4.setFont(font)
        self.label_photo_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_photo_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_photo_4.setObjectName("label_photo_4")
        self.label_name4_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name4_.setGeometry(QtCore.QRect(820, 330, 161, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name4_.setFont(font)
        self.label_name4_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name4_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name4_.setObjectName("label_name4_")
        self.label_number4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number4.setGeometry(QtCore.QRect(730, 400, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number4.setFont(font)
        self.label_number4.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number4.setObjectName("label_number4")
        self.label_name4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name4.setGeometry(QtCore.QRect(730, 330, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name4.setFont(font)
        self.label_name4.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name4.setObjectName("label_name4")
        self.label_name5_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name5_.setGeometry(QtCore.QRect(300, 550, 161, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name5_.setFont(font)
        self.label_name5_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name5_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name5_.setObjectName("label_name5_")
        self.label_number5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number5.setGeometry(QtCore.QRect(210, 620, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number5.setFont(font)
        self.label_number5.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number5.setObjectName("label_number5")
        self.label_number5_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number5_.setGeometry(QtCore.QRect(300, 620, 161, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number5_.setFont(font)
        self.label_number5_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number5_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number5_.setObjectName("label_number5_")
        self.label_photo_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_photo_5.setGeometry(QtCore.QRect(10, 520, 171, 191))
        font = QtGui.QFont()
        font.setFamily("Hobo Std")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_photo_5.setFont(font)
        self.label_photo_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_photo_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_photo_5.setObjectName("label_photo_5")
        self.label_name5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name5.setGeometry(QtCore.QRect(210, 550, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name5.setFont(font)
        self.label_name5.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name5.setObjectName("label_name5")
        self.label_name6_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name6_.setGeometry(QtCore.QRect(820, 550, 161, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name6_.setFont(font)
        self.label_name6_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name6_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name6_.setObjectName("label_name6_")
        self.label_number6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number6.setGeometry(QtCore.QRect(730, 620, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number6.setFont(font)
        self.label_number6.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number6.setObjectName("label_number6")
        self.label_number6_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number6_.setGeometry(QtCore.QRect(820, 620, 161, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number6_.setFont(font)
        self.label_number6_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number6_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number6_.setObjectName("label_number6_")
        self.label_photo_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_photo_6.setGeometry(QtCore.QRect(530, 520, 171, 191))
        font = QtGui.QFont()
        font.setFamily("Hobo Std")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_photo_6.setFont(font)
        self.label_photo_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_photo_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_photo_6.setObjectName("label_photo_6")
        self.label_name6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name6.setGeometry(QtCore.QRect(730, 550, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name6.setFont(font)
        self.label_name6.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name6.setObjectName("label_name6")
        self.label_name7_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name7_.setGeometry(QtCore.QRect(300, 770, 161, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name7_.setFont(font)
        self.label_name7_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name7_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name7_.setObjectName("label_name7_")
        self.label_number7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number7.setGeometry(QtCore.QRect(210, 840, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number7.setFont(font)
        self.label_number7.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number7.setObjectName("label_number7")
        self.label_number7_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number7_.setGeometry(QtCore.QRect(300, 840, 161, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number7_.setFont(font)
        self.label_number7_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number7_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number7_.setObjectName("label_number7_")
        self.label_photo_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_photo_7.setGeometry(QtCore.QRect(10, 740, 171, 191))
        font = QtGui.QFont()
        font.setFamily("Hobo Std")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_photo_7.setFont(font)
        self.label_photo_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_photo_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_photo_7.setObjectName("label_photo_7")
        self.label_name7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name7.setGeometry(QtCore.QRect(210, 770, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name7.setFont(font)
        self.label_name7.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name7.setObjectName("label_name7")
        self.label_name8_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name8_.setGeometry(QtCore.QRect(820, 770, 161, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name8_.setFont(font)
        self.label_name8_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name8_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name8_.setObjectName("label_name8_")
        self.label_number8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number8.setGeometry(QtCore.QRect(730, 840, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number8.setFont(font)
        self.label_number8.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number8.setObjectName("label_number8")
        self.label_number8_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number8_.setGeometry(QtCore.QRect(820, 840, 161, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number8_.setFont(font)
        self.label_number8_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number8_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number8_.setObjectName("label_number8_")
        self.label_photo_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_photo_8.setGeometry(QtCore.QRect(530, 740, 171, 191))
        font = QtGui.QFont()
        font.setFamily("Hobo Std")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_photo_8.setFont(font)
        self.label_photo_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_photo_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_photo_8.setObjectName("label_photo_8")
        self.label_name8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name8.setGeometry(QtCore.QRect(730, 770, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name8.setFont(font)
        self.label_name8.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name8.setObjectName("label_name8")
        self.label_number9_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number9_.setGeometry(QtCore.QRect(300, 1060, 161, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number9_.setFont(font)
        self.label_number9_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number9_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number9_.setObjectName("label_number9_")
        self.label_number9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number9.setGeometry(QtCore.QRect(210, 1060, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number9.setFont(font)
        self.label_number9.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number9.setObjectName("label_number9")
        self.label_photo_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_photo_9.setGeometry(QtCore.QRect(10, 960, 171, 191))
        font = QtGui.QFont()
        font.setFamily("Hobo Std")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_photo_9.setFont(font)
        self.label_photo_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_photo_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_photo_9.setObjectName("label_photo_9")
        self.label_name9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name9.setGeometry(QtCore.QRect(210, 990, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name9.setFont(font)
        self.label_name9.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name9.setObjectName("label_name9")
        self.label_name9_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name9_.setGeometry(QtCore.QRect(300, 990, 161, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name9_.setFont(font)
        self.label_name9_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name9_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name9_.setObjectName("label_name9_")
        self.label_number10_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number10_.setGeometry(QtCore.QRect(820, 1060, 161, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number10_.setFont(font)
        self.label_number10_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number10_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number10_.setObjectName("label_number10_")
        self.label_number10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_number10.setGeometry(QtCore.QRect(730, 1060, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_number10.setFont(font)
        self.label_number10.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_number10.setObjectName("label_number10")
        self.label_photo_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_photo_10.setGeometry(QtCore.QRect(530, 960, 171, 191))
        font = QtGui.QFont()
        font.setFamily("Hobo Std")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_photo_10.setFont(font)
        self.label_photo_10.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.label_photo_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_photo_10.setObjectName("label_photo_10")
        self.label_name10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name10.setGeometry(QtCore.QRect(730, 990, 71, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name10.setFont(font)
        self.label_name10.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name10.setObjectName("label_name10")
        self.label_name10_ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_name10_.setGeometry(QtCore.QRect(820, 990, 161, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name10_.setFont(font)
        self.label_name10_.setStyleSheet("background-color: rgb(96, 100, 110);\n"
"color: rgb(233, 193, 76);")
        self.label_name10_.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name10_.setObjectName("label_name10_")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_right1 = QtWidgets.QLabel(self.centralwidget)
        self.label_right1.setMinimumSize(QtCore.QSize(300, 0))
        self.label_right1.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_right1.setFont(font)
        self.label_right1.setStyleSheet("background-color:transparent; \n"
"color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-bottom:1px solid rgb(255, 255, 255);")
        self.label_right1.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_right1.setObjectName("label_right1")
        self.verticalLayout.addWidget(self.label_right1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lab_zong_ = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lab_zong_.setFont(font)
        self.lab_zong_.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"color: rgb(255, 255, 255);")
        self.lab_zong_.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_zong_.setObjectName("lab_zong_")
        self.gridLayout.addWidget(self.lab_zong_, 0, 1, 1, 1)
        self.lab_dai_ = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lab_dai_.setFont(font)
        self.lab_dai_.setStyleSheet("color: rgb(0, 170, 0);\n"
"background-color: rgb(50, 50, 50);")
        self.lab_dai_.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_dai_.setObjectName("lab_dai_")
        self.gridLayout.addWidget(self.lab_dai_, 2, 1, 1, 1)
        self.lab_zong = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lab_zong.setFont(font)
        self.lab_zong.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"color: rgb(255, 255, 255);")
        self.lab_zong.setObjectName("lab_zong")
        self.gridLayout.addWidget(self.lab_zong, 0, 0, 1, 1)
        self.lab_wei = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lab_wei.setFont(font)
        self.lab_wei.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"color: rgb(247, 102, 119);")
        self.lab_wei.setObjectName("lab_wei")
        self.gridLayout.addWidget(self.lab_wei, 3, 0, 1, 1)
        self.lab_wei_ = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lab_wei_.setFont(font)
        self.lab_wei_.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"color: rgb(247, 102, 119);")
        self.lab_wei_.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_wei_.setObjectName("lab_wei_")
        self.gridLayout.addWidget(self.lab_wei_, 3, 1, 1, 1)
        self.lab_dai = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lab_dai.setFont(font)
        self.lab_dai.setStyleSheet("color: rgb(0, 170, 0);\n"
"background-color: rgb(50, 50, 50);")
        self.lab_dai.setObjectName("lab_dai")
        self.gridLayout.addWidget(self.lab_dai, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label_right2 = QtWidgets.QLabel(self.centralwidget)
        self.label_right2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_right2.setFont(font)
        self.label_right2.setStyleSheet("background-color:transparent; \n"
"color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-bottom:1px solid rgb(255, 255, 255);")
        self.label_right2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_right2.setObjectName("label_right2")
        self.verticalLayout.addWidget(self.label_right2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_shijian = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_shijian.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_shijian.setStyleSheet("QPushButton{\n"
"border:1px solid rgb(255, 255, 255);\n"
"border-top-left-radius:5px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"font: 14pt \"楷体\";\n"
"color:rgb(255, 255, 255);\n"
"background-color:rgb(103, 116, 166);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(123, 140, 199);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgb(83, 95, 135);\n"
"}\n"
"")
        self.pushButton_shijian.setObjectName("pushButton_shijian")
        self.verticalLayout_2.addWidget(self.pushButton_shijian)
        self.pushButton_renyuan = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_renyuan.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_renyuan.setStyleSheet("QPushButton{\n"
"border:1px solid rgb(255, 255, 255);\n"
"border-top-left-radius:5px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"font: 14pt \"楷体\";\n"
"color:rgb(255, 255, 255);\n"
"background-color:rgb(103, 116, 166);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(123, 140, 199);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgb(83, 95, 135);\n"
"}\n"
"")
        self.pushButton_renyuan.setObjectName("pushButton_renyuan")
        self.verticalLayout_2.addWidget(self.pushButton_renyuan)
        self.pushButton_shuaxin = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_shuaxin.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_shuaxin.setStyleSheet("QPushButton{\n"
"border:1px solid rgb(255, 255, 255);\n"
"border-top-left-radius:5px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"font: 14pt \"楷体\";\n"
"color:rgb(255, 255, 255);\n"
"background-color:rgb(103, 116, 166);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(123, 140, 199);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgb(83, 95, 135);\n"
"}\n"
"")
        self.pushButton_shuaxin.setObjectName("pushButton_shuaxin")
        self.verticalLayout_2.addWidget(self.pushButton_shuaxin)
        self.pushButton_daochu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_daochu.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_daochu.setStyleSheet("QPushButton{\n"
"border:1px solid rgb(255, 255, 255);\n"
"border-top-left-radius:5px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"font: 14pt \"楷体\";\n"
"color:rgb(255, 255, 255);\n"
"background-color:rgb(103, 116, 166);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(123, 140, 199);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgb(83, 95, 135);\n"
"}\n"
"")
        self.pushButton_daochu.setObjectName("pushButton_daochu")
        self.verticalLayout_2.addWidget(self.pushButton_daochu)
        self.pushButton_onvideo = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_onvideo.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_onvideo.setStyleSheet("QPushButton{\n"
"border:1px solid rgb(255, 255, 255);\n"
"border-top-left-radius:5px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"font: 14pt \"楷体\";\n"
"color:rgb(255, 255, 255);\n"
"background-color:rgb(103, 116, 166);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(123, 140, 199);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgb(83, 95, 135);\n"
"}\n"
"")
        self.pushButton_onvideo.setObjectName("pushButton_onvideo")
        self.verticalLayout_2.addWidget(self.pushButton_onvideo)
        self.pushButton_off = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_off.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_off.setStyleSheet("QPushButton{\n"
"border:1px solid rgb(255, 255, 255);\n"
"border-top-left-radius:5px;\n"
"border-top-right-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"font: 14pt \"楷体\";\n"
"color:rgb(255, 255, 255);\n"
"background-color:rgb(103, 116, 166);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(123, 140, 199);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgb(83, 95, 135);\n"
"}\n"
"")
        self.pushButton_off.setObjectName("pushButton_off")
        self.verticalLayout_2.addWidget(self.pushButton_off)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1500, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_left1.setText(_translate("MainWindow", "   工 地 实 时 监 控 图 像"))
        self.label_video.setText(_translate("MainWindow", "video"))
        self.label_photo_1.setText(_translate("MainWindow", "photo"))
        self.label_name1.setText(_translate("MainWindow", "姓名："))
        self.label_name1_.setText(_translate("MainWindow", "XXX"))
        self.label_number1.setText(_translate("MainWindow", "工号："))
        self.label_number1_.setText(_translate("MainWindow", "XXX"))
        self.label_number2.setText(_translate("MainWindow", "工号："))
        self.label_name2_.setText(_translate("MainWindow", "XXX"))
        self.label_photo_2.setText(_translate("MainWindow", "photo"))
        self.label_name2.setText(_translate("MainWindow", "姓名："))
        self.label_number2_.setText(_translate("MainWindow", "XXX"))
        self.label_number3.setText(_translate("MainWindow", "工号："))
        self.label_name3_.setText(_translate("MainWindow", "XXX"))
        self.label_photo_3.setText(_translate("MainWindow", "photo"))
        self.label_name3.setText(_translate("MainWindow", "姓名："))
        self.label_number3_.setText(_translate("MainWindow", "XXX"))
        self.tishi.setText(_translate("MainWindow", "检测到xx人未佩戴，显示了xx人，获取此次更多未佩戴人员请导出"))
        self.label_number4_.setText(_translate("MainWindow", "XXX"))
        self.label_photo_4.setText(_translate("MainWindow", "photo"))
        self.label_name4_.setText(_translate("MainWindow", "XXX"))
        self.label_number4.setText(_translate("MainWindow", "工号："))
        self.label_name4.setText(_translate("MainWindow", "姓名："))
        self.label_name5_.setText(_translate("MainWindow", "XXX"))
        self.label_number5.setText(_translate("MainWindow", "工号："))
        self.label_number5_.setText(_translate("MainWindow", "XXX"))
        self.label_photo_5.setText(_translate("MainWindow", "photo"))
        self.label_name5.setText(_translate("MainWindow", "姓名："))
        self.label_name6_.setText(_translate("MainWindow", "XXX"))
        self.label_number6.setText(_translate("MainWindow", "工号："))
        self.label_number6_.setText(_translate("MainWindow", "XXX"))
        self.label_photo_6.setText(_translate("MainWindow", "photo"))
        self.label_name6.setText(_translate("MainWindow", "姓名："))
        self.label_name7_.setText(_translate("MainWindow", "XXX"))
        self.label_number7.setText(_translate("MainWindow", "工号："))
        self.label_number7_.setText(_translate("MainWindow", "XXX"))
        self.label_photo_7.setText(_translate("MainWindow", "photo"))
        self.label_name7.setText(_translate("MainWindow", "姓名："))
        self.label_name8_.setText(_translate("MainWindow", "XXX"))
        self.label_number8.setText(_translate("MainWindow", "工号："))
        self.label_number8_.setText(_translate("MainWindow", "XXX"))
        self.label_photo_8.setText(_translate("MainWindow", "photo"))
        self.label_name8.setText(_translate("MainWindow", "姓名："))
        self.label_number9_.setText(_translate("MainWindow", "XXX"))
        self.label_number9.setText(_translate("MainWindow", "工号："))
        self.label_photo_9.setText(_translate("MainWindow", "photo"))
        self.label_name9.setText(_translate("MainWindow", "姓名："))
        self.label_name9_.setText(_translate("MainWindow", "XXX"))
        self.label_number10_.setText(_translate("MainWindow", "XXX"))
        self.label_number10.setText(_translate("MainWindow", "工号："))
        self.label_photo_10.setText(_translate("MainWindow", "photo"))
        self.label_name10.setText(_translate("MainWindow", "姓名："))
        self.label_name10_.setText(_translate("MainWindow", "XXX"))
        self.label_right1.setText(_translate("MainWindow", "安全帽佩戴情况数据统计"))
        self.lab_zong_.setText(_translate("MainWindow", "1"))
        self.lab_dai_.setText(_translate("MainWindow", "2"))
        self.lab_zong.setText(_translate("MainWindow", "总人数:"))
        self.lab_wei.setText(_translate("MainWindow", "未佩戴人数:"))
        self.lab_wei_.setText(_translate("MainWindow", "3"))
        self.lab_dai.setText(_translate("MainWindow", "佩戴人数:"))
        self.label_right2.setText(_translate("MainWindow", "菜单Menu"))
        self.pushButton_shijian.setText(_translate("MainWindow", "按时间查询未佩戴人员（历史记录）"))
        self.pushButton_renyuan.setText(_translate("MainWindow", "查找工人具体违规信息"))
        self.pushButton_shuaxin.setText(_translate("MainWindow", "刷新未佩戴区域"))
        self.pushButton_daochu.setText(_translate("MainWindow", "导出本次未佩戴人员名单"))
        self.pushButton_onvideo.setText(_translate("MainWindow", "打开摄像头（ON）"))
        self.pushButton_off.setText(_translate("MainWindow", "退出"))
        self.label_number1.setVisible(False)
        self.label_name1.setVisible(False)
        self.label_name1_.setVisible(False)
        self.label_photo_1.setVisible(False)
        self.label_number1_.setVisible(False)
        self.label_number2.setVisible(False)
        self.label_name2.setVisible(False)
        self.label_name2_.setVisible(False)
        self.label_number2_.setVisible(False)
        self.label_photo_2.setVisible(False)
        self.tishi.setVisible(False)
        self.label_name3_.setVisible(False)
        self.label_number3_.setVisible(False)
        self.label_name4.setVisible(False)
        self.label_name4_.setVisible(False)
        self.label_number4_.setVisible(False)
        self.label_number4.setVisible(False)
        self.label_photo_4.setVisible(False)
        self.label_number3.setVisible(False)
        self.label_photo_3.setVisible(False)
        self.label_name3.setVisible(False)
        self.label_name5_.setVisible(False)
        self.label_number5_.setVisible(False)
        self.label_name6.setVisible(False)
        self.label_name6_.setVisible(False)
        self.label_number6_.setVisible(False)
        self.label_number6.setVisible(False)
        self.label_photo_6.setVisible(False)
        self.label_number5.setVisible(False)
        self.label_photo_5.setVisible(False)
        self.label_name5.setVisible(False)
        self.label_name7_.setVisible(False)
        self.label_number7_.setVisible(False)
        self.label_name8.setVisible(False)
        self.label_name8_.setVisible(False)
        self.label_number8_.setVisible(False)
        self.label_number8.setVisible(False)
        self.label_photo_8.setVisible(False)
        self.label_number7.setVisible(False)
        self.label_photo_7.setVisible(False)
        self.label_name7.setVisible(False)
        self.label_name9_.setVisible(False)
        self.label_number9_.setVisible(False)
        self.label_name10.setVisible(False)
        self.label_name10_.setVisible(False)
        self.label_number10_.setVisible(False)
        self.label_number10.setVisible(False)
        self.label_photo_10.setVisible(False)
        self.label_number9.setVisible(False)
        self.label_photo_9.setVisible(False)
        self.label_name9.setVisible(False)
